name       : codeblocks
version    : 17.12
release    : 11
source     :
    - https://netcologne.dl.sourceforge.net/project/codeblocks/Sources/17.12/codeblocks_17.12.tar.xz : 13881a0a72769694e82e531b8e7814d51fbf1fa122c73c5004e186560fbc57e0
license    : GPL-3.0
component  : programming.ide
summary    : A cross platform, free C, C++ and Fortran IDE.
description: |
    Code::Blocks is a free C, C++ and Fortran IDE built to meet the most demanding needs of its users. It is designed to be very extensible and fully configurable.
    Finally, an IDE with all the features you need, having a consistent look, feel and operation across platforms.
    Built around a plugin framework, Code::Blocks can be extended with plugins. Any kind of functionality can be added by installing/coding a plugin. For instance, compiling and debugging functionality is already provided by plugins!
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(sm)
    - bzip2-devel
    - libboost-devel
    - wxwidgets-devel
rundeps    :
    - gfortran
setup      : |
    ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
