name       : codeblocks
version    : 13.12
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/codeblocks/Sources/13.12/codeblocks_13.12-1.tar.gz : 772450046e8c8ba2ea0086acf433a46b83e6254fae64df9c8ca132a22f949610
license    : GPL-3.0
summary    : A cross platform, free C, C++ and Fortran IDE.
description: |
    Code::Blocks is a free C, C++ and Fortran IDE built to meet the most demanding needs of its users. It is designed to be very extensible and fully configurable.
    Finally, an IDE with all the features you need, having a consistent look, feel and operation across platforms.
    Built around a plugin framework, Code::Blocks can be extended with plugins. Any kind of functionality can be added by installing/coding a plugin. For instance, compiling and debugging functionality is already provided by plugins!
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(fontconfig)
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
