name       : codeblocks
version    : '20.03'
release    : 17
source     :
    - https://sourceforge.net/projects/codeblocks/files/Sources/20.03/codeblocks-20.03.tar.xz/download : 15eeb3e28aea054e1f38b0c7f4671b4d4d1116fd05f63c07aa95a91db89eaac5
license    : GPL-3.0-or-later
component  : programming.ide
summary    : A cross platform, free C, C++ and Fortran IDE
description: |
    Code::Blocks is a free C, C++ and Fortran IDE built to meet the most demanding needs of its users. It is designed to be very extensible and fully configurable.
    Finally, an IDE with all the features you need, having a consistent look, feel and operation across platforms.
    Built around a plugin framework, Code::Blocks can be extended with plugins. Any kind of functionality can be added by installing/coding a plugin. For instance, compiling and debugging functionality is already provided by plugins!
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(sm)
    - bzip2-devel
    - libboost-devel
    - wxwidgets-devel
rundeps    :
    - gfortran
setup      : |
    %patch -p1 < $pkgfiles/gcc-11.patch
    ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
